[%
    T = {
        your_payment_of          = "Your payment of",
        has_been_processed       = "has been processed sucessfully!",
        no_amount_was_passed_in  = "No amount was passed in!",
        payment_cancelled        = "Payment was cancelled!",
        payment_refused          = "Payment was refused by issuer!",
        unknown_error            = "Unkown error.",
        contact_library          = "Contact the library for further details!",
        contact_issuer           = "Contact your card issuer for further details!",
        transaction_id           = "Transaction-ID"
    }
%]

