[%
    T = {
        your_payment_of          = "Din betalning av",
        has_been_processed       = "har hanterats!",
        no_amount_was_passed_in  = "Ingen summa skickades!",
        payment_cancelled        = "Betalningen är avbruten!",
        payment_refused          = "Betalningen vägrades av kortutgivaren!",
        unknown_error            = "Okänt fel.",
        contact_library          = "Kontakta biblioteket för mer information!",
        contact_issuer           = "Kontakta in kortutgivare för mer information!",
        transaction_id           = "Transaktionsnummer"
    }
%]

